---
title: "Dog Breeds | Week 5"
subtitle: "Tidy Tuesday"
author: "Michelle Ohh"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
## --- Load libraries
library(tidyverse)
library(stringr)
library(ggradar)
library(cowplot)
library(magick)
library(palettetown)

library(showtext)
font_add_google("Roboto Condensed", "roboto condensed")
font_add_google("Crimson Pro", "Light 300")
font_add_google("Bangers", "Regular 400")
showtext_opts(dpi = 120)
showtext_auto(enable = TRUE)
```

```{r, message=FALSE}
## --- Read in data
breed_traits <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-01/breed_traits.csv')
trait_description <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-01/trait_description.csv')
breed_rank_all <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-01/breed_rank.csv')
```

```{r}
## --- Data wrangling & preprocessing
# Remove unwanted whitespace
breed_traits <- breed_traits %>% 
  mutate(Breed = str_squish(Breed))

breed_rank_all <- breed_rank_all %>% 
  mutate(Breed = str_squish(Breed))

# - Traits
## Select and rename traits
traits_df <- breed_traits %>% 
  select(Breed, `Good With Other Dogs`, `Watchdog/Protective Nature`, 
         `Energy Level`, `Affectionate With Family`, `Trainability Level`, 
         `Barking Level`, `Playfulness Level`) %>% 
  rename("Family Affection" = "Affectionate With Family",
         "Dog Friendliness" = "Good With Other Dogs",
         "Playfulness" = "Playfulness Level",
         "Protectivity" = "Watchdog/Protective Nature",
         "Trainability" = "Trainability Level",
         "Energy" = "Energy Level",
         "Barking" = "Barking Level")

## Filter to terriers
terriers <- traits_df %>% 
  filter(str_detect(Breed, "Terriers"))

## Change to factors
terriers_12 <- terriers %>% 
  slice(1:12) %>% 
  mutate(Breed = factor(Breed,
                        levels = c("Yorkshire Terriers", 
                                   "Boston Terriers", 
                                   "West Highland White Terriers",
                                   "Scottish Terriers", 
                                   "Soft Coated Wheaten Terriers", 
                                   "Airedale Terriers",
                                   "Bull Terriers",
                                   "Russell Terriers",
                                   "Cairn Terriers",
                                   "Staffordshire Bull Terriers",
                                   "American Staffordshire Terriers",
                                   "Rat Terriers")))

# - Ranks
## Filter to 2020 and rename 
rank_2020 <- breed_rank_all %>% 
  select(Breed, `2020 Rank`) %>% 
  rename("rank" = `2020 Rank`)

## Filter to terriers
terriers_rank <- rank_2020 %>% 
  filter(str_detect(Breed, "Terriers"))

## Change to factors
top_terriers <- terriers_rank %>% 
  slice(1:12) %>% 
  mutate(Breed = factor(Breed,
                        levels = c("Yorkshire Terriers", 
                                   "Boston Terriers", 
                                   "West Highland White Terriers",
                                   "Scottish Terriers", 
                                   "Soft Coated Wheaten Terriers", 
                                   "Airedale Terriers",
                                   "Bull Terriers",
                                   "Russell Terriers",
                                   "Cairn Terriers",
                                   "Staffordshire Bull Terriers",
                                   "American Staffordshire Terriers",
                                   "Rat Terriers")))
```

```{r}
## --- Plot
# Main plot
plot <- terriers_12 %>%
  ggradar(grid.min = 1, 
          grid.max = 5,
          values.radar = c(1, 3, 5),
          label.gridline.mid = FALSE,
          axis.label.size = 3,
          axis.label.offset = 1.1,
          group.point.size = 2,
          group.colours = "#b86919",
          gridline.mid.colour = "gray",
          grid.label.size = 0) +
  facet_wrap(vars(group)) + 
  theme(legend.position = "none",
        plot.background = element_rect(fill = "#f4f1eb", colour = "#f4f1eb"),
        panel.background = element_rect(fill = "#f4f1eb"),
        strip.background = element_rect(colour = "black", fill = "#d0c2aa"),
        strip.text = element_text(size = 11, face = "bold",
                                  family = "roboto condensed"))

# Rank label plot
middle <- ggradar(terriers_12,
        grid.min = 1, 
        grid.max = 5,
        values.radar = c(1, 3, 5),
        label.gridline.mid = FALSE,
        axis.label.size = 0,
        group.colours = "#b86919",
        group.line.width = 0,
        group.point.size = -2,
        gridline.mid.colour = "gray",
        grid.label.size = 0,
        background.circle.transparency = 0) +
  geom_text(data = top_terriers, aes(x = 0, y = -0.05, label = rank)) +
  facet_wrap(vars(Breed)) +
  theme(legend.position = "none",
        panel.background = element_blank(),
        plot.background = element_blank(),
        strip.background = element_rect(colour = "black", fill = "#d0c2aa"),
        strip.text = element_text(size = 11, face = "bold",
                                  family = "roboto condensed"))

# Combine plots
ggdraw(plot) +
  theme(plot.margin = margin(1, 1, 0, 1, unit = "cm"),
        plot.background = element_rect(fill = "#f4f1eb")) +
  draw_text(text = "Characteristics of the Top Terriers in 2020", 
            x = 0.5, y = 1.015, size = 20, family = "Regular 400") +
  draw_text(text = "The numbers represent the terrier's rank out of 195 dogs. Each characteristic is rated from 1 (low) to 5 (high).", 
            x = 0.5, y = 0.985, size = 12, family = "Light 300") +
  draw_text(text = "Source: American Kennel Club courtesy of @KKakey | #TidyTuesday Week 5",
            x = 0.84, y = 0.025, size = 10, family = "roboto condensed") +
  draw_plot(middle)

## --- Save plot
ggsave("dog.png", width = 35, height = 25, units = "cm")
```

```{r}
## --- Plot with dog icons
ggdraw(plot) +
  theme(plot.margin = margin(1, 1, 0, 1, unit = "cm"),
        plot.background = element_rect(fill = "#f4f1eb")) +
  draw_text(text = "Characteristics of the Top Terriers in 2020", 
            x = 0.5, y = 1.015, size = 20, family = "Regular 400") +
  draw_text(text = "Each characteristic is rated from 1 (low) to 5 (high).", 
            x = 0.5, y = 0.985, size = 12, family = "Light 300") +
  draw_text(text = "Source: American Kennel Club courtesy of @KKakey | #TidyTuesday Week 5",
            x = 0.84, y = 0.02, size = 10, family = "roboto condensed") + 
  draw_text(text = "Icons by Freepik from Flaticons.com", 
            x = 0.758, y = 0.037, size = 10, family = "roboto condensed") +
  draw_image(here::here("2022/week-5/image/yorkie.png"), x = 0.119, y = 0.779, width = 0.025, height = 0.025) + # yorkie
  draw_image(here::here("2022/week-5/image/boston-terrier.png"), x = 0.366, y = 0.779, width = 0.025, height = 0.025) + # boston
  draw_image(here::here("2022/week-5/image/westie.png"), x = 0.613, y = 0.779, width = 0.025, height = 0.025) + # westie 
  draw_image(here::here("2022/week-5/image/scottish-terrier.png"), x = 0.8605, y = 0.779, width = 0.025, height = 0.025) + # scottish
  draw_image(here::here("2022/week-5/image/soft-terrier.png"), x = 0.119, y = 0.473, width = 0.025, height = 0.025) + # soft
  draw_image(here::here("2022/week-5/image/airedale-terrier.png"), x = 0.366, y = 0.473, width = 0.025, height = 0.025) + # airedale
  draw_image(here::here("2022/week-5/image/bull-terrier.png"), x = 0.613, y = 0.473, width = 0.025, height = 0.025) + # bull
  draw_image(here::here("2022/week-5/image/jack-russell-terrier.png"), x = 0.8605, y = 0.473, width = 0.025, height = 0.025) +# russell
  draw_image(here::here("2022/week-5/image/cairn-terrier.png"), x = 0.119, y = 0.167, width = 0.025, height = 0.025) + # cairn 
  draw_image(here::here("2022/week-5/image/staff.png"), x = 0.366, y = 0.167, width = 0.025, height = 0.025) + # staffy
  draw_image(here::here("2022/week-5/image/american-staff.png"), x = 0.613, y = 0.167, width = 0.025, height = 0.025) + # american staffy
  draw_image(here::here("2022/week-5/image/rat-terrier.png"), x = 0.8605, y = 0.167, width = 0.025, height = 0.025) # rat

## --- Save plot
ggsave("dog_icon.png", width = 35, height = 25, units = "cm")
```

