---
title: "BYOD | Week 1"
subtitle: "Tidy Tuesday"
author: "Michelle Ohh"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
## --- Libraries
library(readr)
library(dplyr)
library(ggplot2)
library(usmap)

library(showtext)
font_add_google("Domine", "Regular 400")
showtext_opts(dpi = 120)
showtext_auto(enable = TRUE)
```

```{r}
## --- Read in data
## Shootings data
shootings <- read_csv(here::here("2022/week-1/data/shootings.csv"))

## US map
us_map <- us_map(regions = "states") %>% 
  select(x, y, abbr, full, group) %>% 
  rename(lat = y, long = x, state = full)

## US states
us_states <- read_csv(here::here("2022/week-1/data/csvData.csv"))

## US population
us_pop <- read_csv(here::here("2022/week-1/data/2019_Census_US_Population_Data_By_State_Lat_Long.csv"))
```

```{r}
## --- Data preprocessing and wrangling
## Add full names of state
shootings <- shootings %>%
  left_join(us_states, by = c("state" = "Code")) %>%
  select(date, State) %>%
  rename(state = State)

## Filter to 2019
shootings_2019 <- shootings %>% 
  filter(date >= "2019-01-01" & date <= "2019-12-31") 

## Count total per state
shootings_state <- shootings_2019 %>%
  group_by(state) %>%
  summarise(total_per_state = n())

## Add population
shootings_state <- shootings_state %>%
  left_join(us_pop, by = c("state" = "STATE")) %>%
  select(state, total_per_state, POPESTIMATE2019) %>%
  rename(population = POPESTIMATE2019)

## Calculate per 100,000 of population
shootings_state <- shootings_state %>%
  mutate(total_per_pop = round(total_per_state*(100000/population), 2))

## Combine with map
shootings_state_map <- us_map %>% 
  left_join(shootings_state, by = "state")

## Replace NAs
shootings_state_map[is.na(shootings_state_map)] <- 0
```

```{r}
## --- Plot
ggplot(shootings_state_map, 
             aes(x = long, y = lat, group = group)) + 
  geom_polygon(color = "black", size = 0.25, 
               aes(group = group, fill = total_per_pop)) + 
  labs(title = "How many police shootings were there in 2019?",
       caption = "Source: Ahsen Nazir | Kaggle",
       fill = "Per 100k of\npopulation") +
  scale_fill_distiller(palette = "OrRd", direction = 1) +
  theme_light(base_family = "Regular 400") +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        legend.title = element_text(size = 9),
        panel.border = element_blank(),
        panel.grid = element_blank(),
        plot.caption = element_text(hjust = 0),
        plot.title = element_text(face = "bold", size = 16))

## --- Save Plot
ggsave("shootings.png", height = 5, width = 8, units = "in")
```
