---
title: "BYOD | Week 1"
subtitle: "Tidy Tuesday"
author: "Michelle Ohh"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
## --- Libraries
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(palettetown)

library(showtext)
font_add_google("Inconsolata", "Semi-bold 600")
showtext_opts(dpi = 120)
showtext_auto(enable = TRUE)
```

```{r message=FALSE}
## --- Read in data
tuesdata <- tidytuesdayR::tt_load('2021-01-26')
plastics <- tuesdata$plastics

## Continents dataset
continents <- read_csv(here::here("2022/week-1/data/countryContinent.csv"))
```

```{r}
## --- Data preprocessing & wrangling
## Top 10 Plastic Polluters in 2020
top10 <- plastics %>% filter(year == "2020") %>% 
  group_by(parent_company) %>% 
  summarise(count = n(),
            total = sum(grand_total, na.rm = TRUE)) %>% 
  arrange(desc(count), desc(total)) %>% 
  slice(-(2:3)) %>% 
  head(10)

## Extract company names
company <- top10 %>% 
  pull(parent_company)

## Filter and minimise dataset
plastics2020 <- plastics %>% 
  filter(year == "2020",
         parent_company %in% company) %>% 
  select(country, parent_company, grand_total)

## Recode country names
plastics2020$country <- recode(plastics2020$country, 
                               "United Kingdom of Great Britain & Northern Ireland" = 
                                 "United Kingdom of Great Britain and Northern Ireland",
                               "Korea" = "Korea (Republic of)",
                               "Tanzania" = "Tanzania, United Republic of",
                               "Vietnam" = "Viet Nam")

## Filter to country and continent
continents <- continents %>% 
  select(country, continent)

## Add continent column
plastics2020 <- plastics2020 %>% 
  left_join(continents, by = "country")

## Convert to factors 
plastics2020 <- plastics2020 %>% 
  mutate(country = factor(country),
         parent_company = factor(parent_company),
         continent = factor(continent))

## Total waste of each company by continent
plastics2020 <- plastics2020 %>% 
  group_by(continent, parent_company) %>% 
  summarise(total = sum(grand_total, na.rm = TRUE))

## --- Calculate percentages 
## Widen
plastics_per <- plastics2020 %>% 
  pivot_wider(names_from = continent, values_from = total)

## Add total
plastics_per <- plastics_per %>% 
  left_join(top10, by = "parent_company")

## Calculate proportion 
plastics_per <- plastics_per %>% 
  mutate(Africa = round((Africa/total)*100, 2),
         Americas = round((Americas/total)*100, 2),
         Asia = round((Asia/total)*100, 2),
         Europe = round((Europe/total)*100, 2),
         Oceania = round((Oceania/total)*100,2))

## Lengthen
plastics_per <- plastics_per %>% 
  pivot_longer(cols = 2:6, names_to = "continent", values_to = "percentage") %>%
  select(continent, parent_company, percentage)

## Convert to factors
plastics_per <- plastics_per %>% 
  mutate(parent_company = factor(parent_company),
         continent = factor(continent))

## Aggregate data 
plastics2020 <- plastics2020 %>% 
  right_join(plastics_per)

## Replace NAs
plastics2020[is.na(plastics2020)] <- 0
```

```{r}
## --- Plot
ggplot(data = plastics2020, aes(x = continent, y = percentage, fill = continent)) +
  geom_col() +
  labs(x = "Continent", y = "Amount of Plastic",
       title = "Where and What Plastics are Polluting the World?",
       subtitle = "The top 10 companies who are the source of the plastic pollution in 2020",
       caption = "Source: Break Free from Plastic by Sarah Sauve") +
  scale_fill_poke(pokemon = 73, name = "Continent") +
  guides(fill = guide_legend(title.position = "top")) +
  theme_bw(base_family = "Semi-bold 600") +
  theme(axis.text.x = element_blank(),
        axis.ticks.x.bottom = element_blank(),
        axis.title.x = element_blank(),
        legend.direction = "horizontal",
        legend.key.size = unit(0.4, "cm"),
        legend.position = c(0.75, 0.2),
        legend.text = element_text(size = 8),
        panel.grid = element_blank(),
        plot.caption = element_text(size = 6, 
                                    hjust = 1),
        plot.title = element_text(face = "bold"),
        plot.subtitle = element_text(size = 9),
        strip.text = element_text(size = 7)) +
  facet_wrap(~parent_company, ncol = 4)

## --- Save plot
ggsave("plastics.png", width = 10, height = 5, units = "in")
```